module.exports.firstNamesMale = [
    'James',
    'Robert',
    'John',
    'Michael',
    'William',
    'David',
    'Richard',
    'Joseph',
    'Thomas',
    'Charles',
    'Christopher',
    'Daniel',
    'Matthew',
    'Anthony',
    'Mark',
    'Donald',
    'Steven',
    'Paul',
    'Andrew',
    'Joshua',
    'Kenneth',
    'Kevin',
    'Brian',
    'George',
    'Edward',
    'Ronald',
    'Timothy',
    'Jason',
    'Jeffrey',
    'Ryan',
    'Jacob',
    'Gary',
    'Nicholas',
    'Eric',
    'Jonathan',
    'Stephen',
    'Larry',
    'Justin',
    'Scott',
    'Brandon',
    'Benjamin',
    'Samuel',
    'Gregory',
    'Frank',
    'Alexander',
    'Raymond',
    'Patrick',
    'Jack',
    'Dennis',
    'Jerry',
    'Tyler',
    'Aaron',
    'Jose',
    'Adam',
    'Henry',
    'Nathan',
    'Douglas',
    'Zachary',
    'Peter',
    'Kyle',
    'Walter',
    'Ethan',
    'Jeremy',
    'Harold',
    'Keith',
    'Christian',
    'Roger',
    'Noah',
    'Gerald',
    'Carl',
    'Terry',
    'Sean',
    'Austin',
    'Arthur',
    'Lawrence',
    'Jesse',
    'Dylan',
    'Bryan',
    'Joe',
    'Jordan',
    'Billy',
    'Bruce',
    'Albert',
    'Willie',
    'Gabriel',
    'Logan',
    'Alan',
    'Juan',
    'Wayne',
    'Roy',
    'Ralph',
    'Randy',
    'Eugene',
    'Vincent',
    'Russell',
    'Elijah',
    'Louis',
    'Bobby',
    'Philip',
    'Johnny',
]

module.exports.firstNamesFemale = [
    'Mary',
    'Patricia',
    'Jennifer',
    'Linda',
    'Elizabeth',
    'Barbara',
    'Susan',
    'Jessica',
    'Sarah',
    'Karen',
    'Nancy',
    'Lisa',
    'Betty',
    'Margaret',
    'Sandra',
    'Ashley',
    'Kimberly',
    'Emily',
    'Donna',
    'Michelle',
    'Dorothy',
    'Carol',
    'Amanda',
    'Melissa',
    'Deborah',
    'Stephanie',
    'Rebecca',
    'Sharon',
    'Laura',
    'Cynthia',
    'Kathleen',
    'Amy',
    'Shirley',
    'Angela',
    'Helen',
    'Anna',
    'Brenda',
    'Pamela',
    'Nicole',
    'Emma',
    'Samantha',
    'Katherine',
    'Christine',
    'Debra',
    'Rachel',
    'Catherine',
    'Carolyn',
    'Janet',
    'Ruth',
    'Maria',
    'Heather',
    'Diane',
    'Virginia',
    'Julie',
    'Joyce',
    'Victoria',
    'Olivia',
    'Kelly',
    'Christina',
    'Lauren',
    'Joan',
    'Evelyn',
    'Judith',
    'Megan',
    'Cheryl',
    'Andrea',
    'Hannah',
    'Martha',
    'Jacqueline',
    'Frances',
    'Gloria',
    'Ann',
    'Teresa',
    'Kathryn',
    'Sara',
    'Janice',
    'Jean',
    'Alice',
    'Madison',
    'Doris',
    'Abigail',
    'Julia',
    'Judy',
    'Grace',
    'Denise',
    'Amber',
    'Marilyn',
    'Beverly',
    'Danielle',
    'Theresa',
    'Sophia',
    'Marie',
    'Diana',
    'Brittany',
    'Natalie',
    'Isabella',
    'Charlotte',
    'Rose',
    'Alexis',
    'Kayla'
]

module.exports.lastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Garcia',
    'Miller',
    'Davis',
    'Rodriguez',
    'Martinez',
    'Hernandez',
    'Lopez',
    'Gonzales',
    'Wilson',
    'Anderson',
    'Thomas',
    'Taylor',
    'Moore',
    'Jackson',
    'Martin',
    'Lee',
    'Perez',
    'Thompson',
    'White',
    'Harris',
    'Sanchez',
    'Clark',
    'Ramirez',
    'Lewis',
    'Robinson',
    'Walker',
    'Young',
    'Allen',
    'King',
    'Wright',
    'Scott',
    'Torres',
    'Nguyen',
    'Hill',
    'Flores',
    'Green',
    'Adams',
    'Nelson',
    'Baker',
    'Hall',
    'Rivera',
    'Campbell',
    'Mitchell',
    'Carter',
    'Roberts',
    'Gomez',
    'Phillips',
    'Evans',
    'Turner',
    'Diaz',
    'Parker',
    'Cruz',
    'Edwards',
    'Collins',
    'Reyes',
    'Stewart',
    'Morris',
    'Morales',
    'Murphy',
    'Cook',
    'Rogers',
    'Gutierrez',
    'Ortiz',
    'Morgan',
    'Cooper',
    'Peterson',
    'Bailey',
    'Reed',
    'Kelly',
    'Howard',
    'Ramos',
    'Kim',
    'Cox',
    'Ward',
    'Richardson',
    'Watson',
    'Brooks',
    'Chavez',
    'Wood',
    'James',
    'Bennet',
    'Gray',
    'Mendoza',
    'Ruiz',
    'Hughes',
    'Price',
    'Alvarez',
    'Castillo',
    'Sanders',
    'Patel',
    'Myers',
    'Long',
    'Ross',
    'Foster',
    'Jimenez'
]

module.exports.imagesMale = [
    "nlZTjUZX2qo",
    "oQfSHQ2Uaic",
    "NXMZxygMw8o",
    "sHfo3WOgGTU",
    "HyvE5SiKMUs",
    "vOZP2LojrHI",
    "BNrqnvtzXio",
    "Z4Q9KHw9ofE",
    "sEJpq3D2vMo",
    "HiL7VHRwQkM",
    "WiKEnlt6Z3U",
    "Jf7hr7ZQzg8",
    "IsSxH3_6WlE",
    "0sa8D74iodI",
    "Th2Pk8NKpOc",
    "sGIp9xdj7kA",
    "dAqJ2hmw3Jc",
    "iUzgePOoGko",
    "irEWJkDxIW8",
    "jAke8NofTtE",
    "ig3Wqug85tA",
    "sf0qE4XehbI",
    "1hI7tt6FMQg",
    "Vu0SzNx1iJw",
    "H6ED86m2TMQ",
    "YVz1LxVJqoA",
    "0eQhWkLfFaU",
    "5bvz74O6r58",
    "yiQCexXTXJI",
    "tBmmA3pTciA"
]

module.exports.imagesFemale = [
    "R0y_bEUjiOM",
    "MCP9atiDcAk",
    "PnUYkTFkOD0",
    "HHXdPG_eTIQ",
    "rfEM2vlm6ak",
    "-l-eemJU0vE",
    "tj27cwu86Wk",
    "n6gnCa77Urc",
    "ZXq7xoo98b0",
    "GaprWyIw66o",
    "rZmCg1_QOYQ",
    "gJtDg6WfMlQ",
    "xQghSLXYD3M",
    "3jAN9InapQI",
    "OD2z4Pn4LXQ",
    "YA-9Ut5B03M",
    "1knFytoiXfI",
    "n23bdrR4Q6I",
    "0JRLjBheqi0",
    "oLStrTTMz2s",
    "U5kQvbQWoG0",
    "poRoZIHGNmM",
    "vumninc21yQ",
    "Vn39uEkX00s",
    "vuZi5zk5W-A",
    "b-JycIqgtS4",
    "AFP680B7mxc",
    "K-DE9UZruLs",
    "9D_rUDe7xvA",
    "DC5akQJyH4I"
]

module.exports.descriptions = [
    "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally",
    "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more",
    "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to",
    "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with",
    "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. 'What's happened to me?' he thought. It wasn't a dream. His room, a proper human",
    "The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! 'Now fax quiz Jack!' my brave"
]

module.exports.serviceLocations = [
    ["In Gym"],
    ["In Home"],
    ["Outside"],
    ["Online"],
    ["In Gym", "In Home"],
    ["In Gym", "Outside"],
    ["In Gym", "Online"],
    ["In Home", "Outside"],
    ["In Home", "Online"],
    ["Outside", "Online"],
    ["In Gym", "In Home", "Outside"],
    ["In Gym", "In Home", "Online"],
    ["In Gym", "Outside", "Online"],
    ["In Home", "Outside", "Online"],
    ["In Gym", "In Home", "Outside", "Online"]
]

module.exports.services = [
    ["Training"],
    ["Nutrition"],
    ["Training", "Nutrition"]
]

module.exports.certifications = [
    ["ISSA"],
    ["NCSF"],
    ["FM"],
    ["ACE"],
    ["NASM"],
    ["ISSA", "NCSF"],
    ["ISSA", "FM"],
    ["ISSA", "ACE"],
    ["ISSA", "NASM"],
    ["NCSF", "FM"],
    ["NCSF", "ACE"],
    ["NCSF", "NASM"],
    ["FM", "ACE"],
    ["FM", "NASM"],
    ["ACE", "NASM"],
    ["ISSA", "NCSF", "FM"],
    ["ISSA", "NCSF", "ACE"],
    ["ISSA", "NCSF", "NASM"],
    ["ISSA", "FM", "ACE"],
    ["ISSA", "FM", "NASM"],
    ["ISSA", "ACE", "NASM"],
    ["NCSF", "FM", "ACE"],
    ["NCSF", "FM", "NASM"],
    ["NCSF", "ACE", "NASM"],
    ["FM", "ACE", "NASM"],
    ["ISSA", "NCSF", "FM", "ACE"],
    ["ISSA", "NCSF", "FM", "NASM"],
    ["ISSA", "NCSF", "ACE", "NASM"],
    ["ISSA", "FM", "ACE", "NASM"],
    ["NCSF", "FM", "ACE", "NASM"],
    ["ISSA", "NCSF", "FM", "ACE", "NASM"]
]